apiVersion: v1
kind: Service
metadata:
  annotations:
    datacenter-generation: "1"
  creationTimestamp: "2020-01-16T10:17:50Z"
  labels:
    app: elassandra
    app.kubernetes.io/managed-by: elassandra-operator
    cluster: orchid
    datacenter: dc1
    parent: elassandra-orchid-dc1
  name: elassandra-orchid-dc1-external
  namespace: default
  ownerReferences:
  - apiVersion: stable.strapdata.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: ElassandraDataCenter
    name: elassandra-orchid-dc1
    uid: 734f1151-3849-11ea-8c29-6255ee7682b2
  resourceVersion: "2931325"
  selfLink: /api/v1/namespaces/default/services/elassandra-orchid-dc1-external
  uid: 736bdbed-3849-11ea-8c29-6255ee7682b2
spec:
  clusterIP: 10.0.66.136
  externalTrafficPolicy: Cluster
  ports:
  - name: internode
    nodePort: 32463
    port: 37001
    protocol: TCP
    targetPort: 37001
  - name: cql
    nodePort: 30764
    port: 39042
    protocol: TCP
    targetPort: 39042
  - name: elasticsearch
    nodePort: 32085
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: jmx
    nodePort: 32166
    port: 7199
    protocol: TCP
    targetPort: 7199
  selector:
    datacenter: dc1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
